[package]
name = "voe-cli"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "ve"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.13.5", default-features = false, features = ["json", "rustls"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
clap = { version = "4.6.7", features = ["derive"] }
aes-gcm = "0.11.1"
sha2 = "0.10"
base64 = "0.23.1"
regex = "1.13.1"
self-replace = "1.5.0"
tempfile = "3.27.0"

rsa = { version = "0.9", features = ["sha2"] }
rand = "0.8"
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service", "vendored"] }
uuid = { version = "1", features = ["v4"] }
zeroize = "1"
dotenvy = "0.15"
